matrix:
  include:
    - language: python
      python: 3.8.2
      before_install:
        - cd backend/
      install:
        - pip install pipenv && pipenv install
      script:
        - coverage run manage.py test
      after_success:
        - codecov
    - language: node_js
      node_js: 10.13
      before_install:
        - cd frontend/
      install:
        - npm install
      script:
        - npm run test:unit
      after_success:
        - ./node_modules/.bin/codecov --disable=gcov
notifications:
  email: false
